---
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins:
  - git
  - sonar
  - ssh
  - cobertura
  - jira
  - job-import-plugin
  - plain-credentials
  - rally-plugin
  - stash-pullrequest-builder
  - stashNotifier
  - token-macro
  - workflow-step-api
  - view-job-filters
  - job-dsl
jenkins_url_prefix: ""



